export const mockIssues: any[] = [
    
    {
        "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14",
        "repository_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend",
        "labels_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14/labels{/name}",
        "comments_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14/comments",
        "events_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14/events",
        "html_url": "https://github.com/mishasinitcyn/RepoCleanup-backend/issues/14",
        "id": 2355373436,
        "node_id": "I_kwDOMEfBEs6MZCV8",
        "number": 14,
        "title": "Sprint-3 Update Exploratory Data Analysis",
        "user": {
            "login": "mishasinitcyn",
            "id": 45673816,
            "node_id": "MDQ6VXNlcjQ1NjczODE2",
            "avatar_url": "https://avatars.githubusercontent.com/u/45673816?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mishasinitcyn",
            "html_url": "https://github.com/mishasinitcyn",
            "followers_url": "https://api.github.com/users/mishasinitcyn/followers",
            "following_url": "https://api.github.com/users/mishasinitcyn/following{/other_user}",
            "gists_url": "https://api.github.com/users/mishasinitcyn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mishasinitcyn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mishasinitcyn/subscriptions",
            "organizations_url": "https://api.github.com/users/mishasinitcyn/orgs",
            "repos_url": "https://api.github.com/users/mishasinitcyn/repos",
            "events_url": "https://api.github.com/users/mishasinitcyn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mishasinitcyn/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 7057394422,
                "node_id": "LA_kwDOMEfBEs8AAAABpKdK9g",
                "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/labels/ml",
                "name": "bug",
                "color": "FA4CAB",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": {
            "login": "durgeshfirake",
            "id": 160331991,
            "node_id": "U_kgDOCY541w",
            "avatar_url": "https://avatars.githubusercontent.com/u/160331991?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/durgeshfirake",
            "html_url": "https://github.com/durgeshfirake",
            "followers_url": "https://api.github.com/users/durgeshfirake/followers",
            "following_url": "https://api.github.com/users/durgeshfirake/following{/other_user}",
            "gists_url": "https://api.github.com/users/durgeshfirake/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/durgeshfirake/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/durgeshfirake/subscriptions",
            "organizations_url": "https://api.github.com/users/durgeshfirake/orgs",
            "repos_url": "https://api.github.com/users/durgeshfirake/repos",
            "events_url": "https://api.github.com/users/durgeshfirake/events{/privacy}",
            "received_events_url": "https://api.github.com/users/durgeshfirake/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "durgeshfirake",
                "id": 160331991,
                "node_id": "U_kgDOCY541w",
                "avatar_url": "https://avatars.githubusercontent.com/u/160331991?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/durgeshfirake",
                "html_url": "https://github.com/durgeshfirake",
                "followers_url": "https://api.github.com/users/durgeshfirake/followers",
                "following_url": "https://api.github.com/users/durgeshfirake/following{/other_user}",
                "gists_url": "https://api.github.com/users/durgeshfirake/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/durgeshfirake/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/durgeshfirake/subscriptions",
                "organizations_url": "https://api.github.com/users/durgeshfirake/orgs",
                "repos_url": "https://api.github.com/users/durgeshfirake/repos",
                "events_url": "https://api.github.com/users/durgeshfirake/events{/privacy}",
                "received_events_url": "https://api.github.com/users/durgeshfirake/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2024-06-16T01:45:43Z",
        "updated_at": "2024-06-16T01:45:43Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "## Location\r\n`EDA/exploratory_data_analysis.ipynb`\r\n\r\n## Tasks\r\n- Import dataset-v2\r\n- Pre-process data\r\n- Run existing EDA\r\n- Add [wordclouds](https://medium.com/@m3redithw/wordclouds-with-python-c287887acc8b) for spam and not-spam classes\r\n- Clusters Analysis (in a separate notebook if you prefer), trying different dimensionality reduction algorithms like PCA and TSNE with our two vectorizers CountVectorizer and TFIDFVectorizer. [read this for reference](https://github.com/olekscode/Examples-PCA-tSNE/blob/master/Python/Visualizing%20Iris%20Dataset%20using%20PCA%20and%20t-SNE.ipynb)\r\n\r\n## Optional\r\n- Try Latent Dirichlet Allocation (LDA) with pyLDAvis. [read this for reference](https://neptune.ai/blog/pyldavis-topic-modelling-exploration-tool-that-every-nlp-data-scientist-should-know)",
        "reactions": {
            "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    },
    {
        "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/13",
        "repository_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend",
        "labels_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/13/labels{/name}",
        "comments_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/13/comments",
        "events_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/13/events",
        "html_url": "https://github.com/mishasinitcyn/RepoCleanup-backend/issues/13",
        "id": 2355369526,
        "node_id": "I_kwDOMEfBEs6MZBY2",
        "number": 13,
        "title": "Sprint-3 Rerun scikit-learn binary classifier experiments",
        "user": {
            "login": "mishasinitcyn",
            "id": 45673816,
            "node_id": "MDQ6VXNlcjQ1NjczODE2",
            "avatar_url": "https://avatars.githubusercontent.com/u/45673816?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mishasinitcyn",
            "html_url": "https://github.com/mishasinitcyn",
            "followers_url": "https://api.github.com/users/mishasinitcyn/followers",
            "following_url": "https://api.github.com/users/mishasinitcyn/following{/other_user}",
            "gists_url": "https://api.github.com/users/mishasinitcyn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mishasinitcyn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mishasinitcyn/subscriptions",
            "organizations_url": "https://api.github.com/users/mishasinitcyn/orgs",
            "repos_url": "https://api.github.com/users/mishasinitcyn/repos",
            "events_url": "https://api.github.com/users/mishasinitcyn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mishasinitcyn/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 7035112815,
                "node_id": "LA_kwDOMEfBEs8AAAABo1NNbw",
                "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/labels/enhancement",
                "name": "feature",
                "color": "a2eeef",
                "default": true,
                "description": "New feature or request"
            },
            {
                "id": 7057394422,
                "node_id": "LA_kwDOMEfBEs8AAAABpKdK9g",
                "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/labels/ml",
                "name": "ml",
                "color": "FA4CAB",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2024-06-16T01:34:35Z",
        "updated_at": "2024-06-16T01:34:35Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "## Location\r\n- `binary_spam_classifier_experiments.ipynb`\r\n- `binary_spam_classifier.ipynb`\r\n- `binary_spam_classifier_UI.py`\r\n\r\n## Expectation\r\n- Evaluate the models and vectorizers on dataset-v2\r\n- Record all the evaluations in MLflow\r\n- Train the best performing classifier-vectorizer pair on the full dataset and save in MLflow\r\n- Update the Gradio UI with the newest classifier\r\n\r\n## Setup\r\n- Make sure to install the updated requirements with `pip install -r requirements.txt`\r\n- Run MLflow locally with `mlflow server --backend-store-uri sqlite:///mlruns.db`\r\n- For more info on MLflow, refer to the Documentation page on Notion\r\n- To run the classifier UI with Gradio, run `python binary_spam_classifier_UI,py` in models/",
        "reactions": {
            "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/13/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/13/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    },
    {
        "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/9",
        "repository_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend",
        "labels_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/9/labels{/name}",
        "comments_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/9/comments",
        "events_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/9/events",
        "html_url": "https://github.com/mishasinitcyn/RepoCleanup-backend/pull/9",
        "id": 2349863701,
        "node_id": "PR_kwDOMEfBEs5yS8Y9",
        "number": 9,
        "title": "Sprint-2 Expand dataset with spam issues",
        "user": {
            "login": "dyzhuu",
            "id": 119282717,
            "node_id": "U_kgDOBxwcHQ",
            "avatar_url": "https://avatars.githubusercontent.com/u/119282717?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/dyzhuu",
            "html_url": "https://github.com/dyzhuu",
            "followers_url": "https://api.github.com/users/dyzhuu/followers",
            "following_url": "https://api.github.com/users/dyzhuu/following{/other_user}",
            "gists_url": "https://api.github.com/users/dyzhuu/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/dyzhuu/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/dyzhuu/subscriptions",
            "organizations_url": "https://api.github.com/users/dyzhuu/orgs",
            "repos_url": "https://api.github.com/users/dyzhuu/repos",
            "events_url": "https://api.github.com/users/dyzhuu/events{/privacy}",
            "received_events_url": "https://api.github.com/users/dyzhuu/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [{
            "id": 7057394422,
            "node_id": "LA_kwDOMEfBEs8AAAABpKdK9g",
            "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/labels/ml",
            "name": "discussion",
            "color": "FA4CAB",
            "default": false,
            "description": ""
        }],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2024-06-12T23:57:00Z",
        "updated_at": "2024-06-18T03:14:14Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/pulls/9",
            "html_url": "https://github.com/mishasinitcyn/RepoCleanup-backend/pull/9",
            "diff_url": "https://github.com/mishasinitcyn/RepoCleanup-backend/pull/9.diff",
            "patch_url": "https://github.com/mishasinitcyn/RepoCleanup-backend/pull/9.patch",
            "merged_at": null
        },
        "body": "## Summary\r\n\r\nAdded a spam issues dataset consisting of ~560 issues, manually fetched from repos with lots of spam.",
        "reactions": {
            "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/9/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/9/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    },
    {
        "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/7",
        "repository_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend",
        "labels_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/7/labels{/name}",
        "comments_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/7/comments",
        "events_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/7/events",
        "html_url": "https://github.com/mishasinitcyn/RepoCleanup-backend/issues/7",
        "id": 2341981555,
        "node_id": "I_kwDOMEfBEs6Ll81z",
        "number": 7,
        "title": "Sprint-2 BERT binary classifier experiments",
        "user": {
            "login": "mishasinitcyn",
            "id": 45673816,
            "node_id": "MDQ6VXNlcjQ1NjczODE2",
            "avatar_url": "https://avatars.githubusercontent.com/u/45673816?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mishasinitcyn",
            "html_url": "https://github.com/mishasinitcyn",
            "followers_url": "https://api.github.com/users/mishasinitcyn/followers",
            "following_url": "https://api.github.com/users/mishasinitcyn/following{/other_user}",
            "gists_url": "https://api.github.com/users/mishasinitcyn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mishasinitcyn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mishasinitcyn/subscriptions",
            "organizations_url": "https://api.github.com/users/mishasinitcyn/orgs",
            "repos_url": "https://api.github.com/users/mishasinitcyn/repos",
            "events_url": "https://api.github.com/users/mishasinitcyn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mishasinitcyn/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 7057394422,
                "node_id": "LA_kwDOMEfBEs8AAAABpKdK9g",
                "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/labels/ml",
                "name": "ml",
                "color": "FA4CAB",
                "default": false,
                "description": ""
            },
            {
                "id": 7057398705,
                "node_id": "LA_kwDOMEfBEs8AAAABpKdbsQ",
                "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/labels/advanced",
                "name": "advanced",
                "color": "8933E5",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2024-06-09T02:23:55Z",
        "updated_at": "2024-06-09T02:23:55Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "## Location\r\n`binary_spam_classifier_BERT.ipynb`\r\n\r\n## Expectation\r\n- Follow notebook instructions and provided links\r\n- Fine-tune and evaluate BERT on the first version of the dataset\r\n- Experiment with hyperparameters (optional as it doesn't make a giant difference)\r\n- Record all the evaluations in MLflow\r\n\r\n## Setup\r\n- Add pytorch, transformers, and other mandatory packages to requirements.txt (or torch_requirements.txt for separation)\r\n- Make sure to install the updated requirements with `pip install -r requirements.txt`\r\n- Run MLflow locally with `mlflow server --backend-store sqlite:///mlruns.db`\r\n- For more info on MLflow, refer to the Documentation page on Notion\r\n\r\n## Note\r\n**This is a computationally heavy task**\r\n**This is an advanced deep learning task**",
        "reactions": {
            "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/7/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/7/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    },
    {
        "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/6",
        "repository_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend",
        "labels_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/6/labels{/name}",
        "comments_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/6/comments",
        "events_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/6/events",
        "html_url": "https://github.com/mishasinitcyn/RepoCleanup-backend/issues/6",
        "id": 2341970251,
        "node_id": "I_kwDOMEfBEs6Ll6FL",
        "number": 6,
        "title": "Sprint-2 Expand dataset with more spam issues",
        "user": {
            "login": "mishasinitcyn",
            "id": 45673816,
            "node_id": "MDQ6VXNlcjQ1NjczODE2",
            "avatar_url": "https://avatars.githubusercontent.com/u/45673816?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mishasinitcyn",
            "html_url": "https://github.com/mishasinitcyn",
            "followers_url": "https://api.github.com/users/mishasinitcyn/followers",
            "following_url": "https://api.github.com/users/mishasinitcyn/following{/other_user}",
            "gists_url": "https://api.github.com/users/mishasinitcyn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mishasinitcyn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mishasinitcyn/subscriptions",
            "organizations_url": "https://api.github.com/users/mishasinitcyn/orgs",
            "repos_url": "https://api.github.com/users/mishasinitcyn/repos",
            "events_url": "https://api.github.com/users/mishasinitcyn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mishasinitcyn/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 7035112808,
                "node_id": "LA_kwDOMEfBEs8AAAABo1NNaA",
                "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/labels/documentation",
                "name": "documentation",
                "color": "0075ca",
                "default": true,
                "description": "Improvements or additions to documentation"
            },
            {
                "id": 7040718643,
                "node_id": "LA_kwDOMEfBEs8AAAABo6jXMw",
                "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/labels/data",
                "name": "data",
                "color": "2666D6",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": {
            "login": "mishasinitcyn",
            "id": 45673816,
            "node_id": "MDQ6VXNlcjQ1NjczODE2",
            "avatar_url": "https://avatars.githubusercontent.com/u/45673816?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mishasinitcyn",
            "html_url": "https://github.com/mishasinitcyn",
            "followers_url": "https://api.github.com/users/mishasinitcyn/followers",
            "following_url": "https://api.github.com/users/mishasinitcyn/following{/other_user}",
            "gists_url": "https://api.github.com/users/mishasinitcyn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mishasinitcyn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mishasinitcyn/subscriptions",
            "organizations_url": "https://api.github.com/users/mishasinitcyn/orgs",
            "repos_url": "https://api.github.com/users/mishasinitcyn/repos",
            "events_url": "https://api.github.com/users/mishasinitcyn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mishasinitcyn/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "mishasinitcyn",
                "id": 45673816,
                "node_id": "MDQ6VXNlcjQ1NjczODE2",
                "avatar_url": "https://avatars.githubusercontent.com/u/45673816?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mishasinitcyn",
                "html_url": "https://github.com/mishasinitcyn",
                "followers_url": "https://api.github.com/users/mishasinitcyn/followers",
                "following_url": "https://api.github.com/users/mishasinitcyn/following{/other_user}",
                "gists_url": "https://api.github.com/users/mishasinitcyn/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mishasinitcyn/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mishasinitcyn/subscriptions",
                "organizations_url": "https://api.github.com/users/mishasinitcyn/orgs",
                "repos_url": "https://api.github.com/users/mishasinitcyn/repos",
                "events_url": "https://api.github.com/users/mishasinitcyn/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mishasinitcyn/received_events",
                "type": "User",
                "site_admin": false
            },
            {
                "login": "Davicci",
                "id": 52129316,
                "node_id": "MDQ6VXNlcjUyMTI5MzE2",
                "avatar_url": "https://avatars.githubusercontent.com/u/52129316?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Davicci",
                "html_url": "https://github.com/Davicci",
                "followers_url": "https://api.github.com/users/Davicci/followers",
                "following_url": "https://api.github.com/users/Davicci/following{/other_user}",
                "gists_url": "https://api.github.com/users/Davicci/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Davicci/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Davicci/subscriptions",
                "organizations_url": "https://api.github.com/users/Davicci/orgs",
                "repos_url": "https://api.github.com/users/Davicci/repos",
                "events_url": "https://api.github.com/users/Davicci/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Davicci/received_events",
                "type": "User",
                "site_admin": false
            },
            {
                "login": "xzd9326",
                "id": 103522153,
                "node_id": "U_kgDOBiufaQ",
                "avatar_url": "https://avatars.githubusercontent.com/u/103522153?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/xzd9326",
                "html_url": "https://github.com/xzd9326",
                "followers_url": "https://api.github.com/users/xzd9326/followers",
                "following_url": "https://api.github.com/users/xzd9326/following{/other_user}",
                "gists_url": "https://api.github.com/users/xzd9326/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/xzd9326/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/xzd9326/subscriptions",
                "organizations_url": "https://api.github.com/users/xzd9326/orgs",
                "repos_url": "https://api.github.com/users/xzd9326/repos",
                "events_url": "https://api.github.com/users/xzd9326/events{/privacy}",
                "received_events_url": "https://api.github.com/users/xzd9326/received_events",
                "type": "User",
                "site_admin": false
            },
            {
                "login": "dyzhuu",
                "id": 119282717,
                "node_id": "U_kgDOBxwcHQ",
                "avatar_url": "https://avatars.githubusercontent.com/u/119282717?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/dyzhuu",
                "html_url": "https://github.com/dyzhuu",
                "followers_url": "https://api.github.com/users/dyzhuu/followers",
                "following_url": "https://api.github.com/users/dyzhuu/following{/other_user}",
                "gists_url": "https://api.github.com/users/dyzhuu/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/dyzhuu/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/dyzhuu/subscriptions",
                "organizations_url": "https://api.github.com/users/dyzhuu/orgs",
                "repos_url": "https://api.github.com/users/dyzhuu/repos",
                "events_url": "https://api.github.com/users/dyzhuu/events{/privacy}",
                "received_events_url": "https://api.github.com/users/dyzhuu/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2024-06-09T01:38:15Z",
        "updated_at": "2024-06-09T01:38:16Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "## Location\r\n`ETL/`, create new notebook\r\n\r\n## Expectation\r\n- Download and explore \"spam\" data from non-GitHub sources such as YouTube comments and emails",
        "reactions": {
            "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/6/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/6/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    },
    {
        "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14",
        "repository_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend",
        "labels_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14/labels{/name}",
        "comments_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14/comments",
        "events_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14/events",
        "html_url": "https://github.com/mishasinitcyn/RepoCleanup-backend/issues/14",
        "id": 1,
        "node_id": "I_kwDOMEfBEs6MZCV8",
        "number": 14,
        "title": "Obviously Spam",
        "user": {
            "login": "mishasinitcyn",
            "id": 45673816,
            "node_id": "MDQ6VXNlcjQ1NjczODE2",
            "avatar_url": "https://avatars.githubusercontent.com/u/45673816?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mishasinitcyn",
            "html_url": "https://github.com/mishasinitcyn",
            "followers_url": "https://api.github.com/users/mishasinitcyn/followers",
            "following_url": "https://api.github.com/users/mishasinitcyn/following{/other_user}",
            "gists_url": "https://api.github.com/users/mishasinitcyn/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mishasinitcyn/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mishasinitcyn/subscriptions",
            "organizations_url": "https://api.github.com/users/mishasinitcyn/orgs",
            "repos_url": "https://api.github.com/users/mishasinitcyn/repos",
            "events_url": "https://api.github.com/users/mishasinitcyn/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mishasinitcyn/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 7057394422,
                "node_id": "LA_kwDOMEfBEs8AAAABpKdK9g",
                "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/labels/ml",
                "name": "bug",
                "color": "FA4CAB",
                "default": false,
                "description": ""
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": {
            "login": "durgeshfirake",
            "id": 160331991,
            "node_id": "U_kgDOCY541w",
            "avatar_url": "https://avatars.githubusercontent.com/u/160331991?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/durgeshfirake",
            "html_url": "https://github.com/durgeshfirake",
            "followers_url": "https://api.github.com/users/durgeshfirake/followers",
            "following_url": "https://api.github.com/users/durgeshfirake/following{/other_user}",
            "gists_url": "https://api.github.com/users/durgeshfirake/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/durgeshfirake/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/durgeshfirake/subscriptions",
            "organizations_url": "https://api.github.com/users/durgeshfirake/orgs",
            "repos_url": "https://api.github.com/users/durgeshfirake/repos",
            "events_url": "https://api.github.com/users/durgeshfirake/events{/privacy}",
            "received_events_url": "https://api.github.com/users/durgeshfirake/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "durgeshfirake",
                "id": 160331991,
                "node_id": "U_kgDOCY541w",
                "avatar_url": "https://avatars.githubusercontent.com/u/160331991?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/durgeshfirake",
                "html_url": "https://github.com/durgeshfirake",
                "followers_url": "https://api.github.com/users/durgeshfirake/followers",
                "following_url": "https://api.github.com/users/durgeshfirake/following{/other_user}",
                "gists_url": "https://api.github.com/users/durgeshfirake/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/durgeshfirake/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/durgeshfirake/subscriptions",
                "organizations_url": "https://api.github.com/users/durgeshfirake/orgs",
                "repos_url": "https://api.github.com/users/durgeshfirake/repos",
                "events_url": "https://api.github.com/users/durgeshfirake/events{/privacy}",
                "received_events_url": "https://api.github.com/users/durgeshfirake/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2024-06-16T01:45:43Z",
        "updated_at": "2024-06-16T01:45:43Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "Plz give free bitcoin now",
        "reactions": {
            "url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/mishasinitcyn/RepoCleanup-backend/issues/14/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    },
]